version: '3'

services:
  abecede-web:
    container_name: abecede-web
    build:
      context: .
      dockerfile: Dockerfile
    image: abecede-web:latest
    ports:
      - "8081:80" # Host Port : Container Port (Host 8081 -> Container 80)
    restart: always
    volumes:
      - ./front:/usr/share/nginx/html # Optional: Mount for hot-reloading changes without rebuild
